# Name: Yash Gulati
# SAP ID: 500083348
# ROLL NO: R2142201335
# Batch: 1
# Course: Container Orchestration and Infrastructure Automation


# syntax=docker/dockerfile:1
FROM python:latest

WORKDIR /app

COPY . .

CMD [ "python", "server/server.py" ]